name: "Run SAST, Build and push supermario image, scan image, Update deployment and version files"

on:
  push:
    branches:
      - main

jobs:
  sonarqube_sast_scan:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setver.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read and bump VERSION
        id: setver
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -f version.txt ]; then
            echo "version.txt not found"
            exit 1
          fi

          raw=$(cat version.txt | tr -d '[:space:]')
          if ! [[ "$raw" =~ ^[0-9]+$ ]]; then
            echo "version.txt must contain only a number. Found: '$raw'"
            exit 1
          fi

          v=$((raw + 1))
          echo "version=$v" >> "$GITHUB_OUTPUT"
          echo "Next VERSION will be: $v"

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_push_supermario_docker_image:
    runs-on: ubuntu-latest
    needs: sonarqube_sast_scan
    env:
      VERSION: ${{ needs.sonarqube_sast_scan.outputs.version }}
      IMAGE: docker.io/dbakeytest/supermariogitopsproject

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify VERSION
        shell: bash
        run: |
          set -euo pipefail
          echo "VERSION=$VERSION"
          if [ -z "$VERSION" ]; then
            echo "VERSION is empty, stopping."
            exit 1
          fi

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        shell: bash
        run: |
          set -euo pipefail
          docker build -t "${IMAGE}:${VERSION}" .
          docker push "${IMAGE}:${VERSION}"

  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest
    needs: build_push_supermario_docker_image
    env:
      VERSION: ${{ needs.sonarqube_sast_scan.outputs.version }}
      IMAGE: docker.io/dbakeytest/supermariogitopsproject

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify VERSION
        shell: bash
        run: |
          set -euo pipefail
          echo "VERSION=$VERSION"
          if [ -z "$VERSION" ]; then
            echo "VERSION is empty, stopping."
            exit 1
          fi

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Get Docker Image from Docker Hub
        shell: bash
        run: |
          set -euo pipefail
          docker pull "${IMAGE}:${VERSION}"
          docker save -o supermariolatestdockerimage.tar "${IMAGE}:${VERSION}"

      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          input: /github/workspace/supermariolatestdockerimage.tar
          exit-code: "0"
          severity: "CRITICAL,HIGH"

  update_k8s_yaml_version_file_with_latest_image_tag:
    runs-on: ubuntu-latest
    needs: run_container_image_scan_on_supermario_docker_image
    env:
      VERSION: ${{ needs.sonarqube_sast_scan.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set Git Config
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"

      - name: Update Deployment YAML and version.txt
        shell: bash
        run: |
          set -euo pipefail

          if [ -z "$VERSION" ]; then
            echo "VERSION is empty, stopping."
            exit 1
          fi

          sed -i -E "s|(image:\s*dbakeytest/supermariogitopsproject:).*|\1${VERSION}|" deployment.yaml
          echo "${VERSION}" > version.txt

          git add deployment.yaml version.txt
          git commit -m "Update deployment and version to ${VERSION}" || echo "No changes to commit"
          git push